name: Setup
description: "Setup the environment"

runs:
  using: composite
  steps:
    - uses: jdx/mise-action@c94f0bf9e520b150e34c017db785461f7e71c5fb # v2.2.2
      with:
        experimental: true
