version: 2

builds:
  - ldflags:
      - -s -w -X github.com/koki-develop/clive/cmd.version=v{{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

source:
  enabled: true

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: 'checksums.txt'

brews:
  - repository:
      owner: koki-develop
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/koki-develop/clive
    description: Automates terminal operations and lets you view them live via a browser
    dependencies:
      - name: ttyd
    test: |
      system "#{bin}/clive", "init"
      system "#{bin}/clive", "validate"
      assert_match "clive version v#{version}", shell_output("#{bin}/clive --version")
